In [ ]:
#Problem 1

In [4]:
import numpy as np
a = np.random.randint(1, 51, size=(5, 4))

In [8]:
random_array = np.random.randint(1, 51, size=(5, 4))
print(random_array)

[[18  2 39 29]
 [45 13 31 33]
 [39  9 24 31]
 [48 12 19 33]
 [45 32  9 28]]


In [9]:
anti_diagonal = np.fliplr(random_array).diagonal()
print(anti_diagonal)

[29 31  9 48]


In [ ]:
#1.2

In [10]:
row_max = np.max(random_array, axis=1)
print(row_max)

[39 45 39 48 45]


In [ ]:
#1.3

In [11]:
mean_value = np.mean(random_array)
filtered_array = random_array[random_array <= mean_value]
print(filtered_array)

[18  2 13  9 24 12 19  9]


In [ ]:
#1.4

In [13]:
def numpy_boundary_traversal(matrix):
    if matrix.size == 0:
        return []
    top = matrix[0, :].tolist()
    right = matrix[1:, -1].tolist()
    bottom = matrix[-1, :-1][::-1].tolist() if matrix.shape[0] > 1 else []
    left = matrix[1:-1, 0][::-1].tolist() if matrix.shape[1] > 1 else []
    return top + right + bottom + left